[build]
  publish = "."

[[redirects]]
  from = "/catalogo-2"
  to = "/cole-40-41"
  status = 301

[[redirects]]
  from = "/catalogo-2.html"
  to = "/cole-40-41"
  status = 301

[[redirects]]
  from = "/cole-40-41"
  to = "/catalogo-2.html"
  status = 200

[[redirects]]
  from = "/cole-40-41.html"
  to = "/cole-40-41"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
